RMRPA-17 Moving of closed issues now adds fixversion instead of repla…
re-motion/ReleaseProcessAutomation pull request #2
Opened 2022-12-14 14:39 UTC by Frazerus

https://re-motion.atlassian.net/browse/RMRPA-17

2022-12-20 11:56 UTC, a-ctor approved these changes

2022-12-20 11:56 UTC, a-ctor commented on Core/Steps/SubSteps/ReleaseVersionAndMoveIssuesSubStep.cs
> +      _console.WriteLine(message.Substring(0, length) + "'");
Since the key has a fixed width wouldn't it be easier to limit just the length of the summary? Right now it is hard to see what is actually printed since the parts are so split up. We are also missing the ellipsis `...` which makes the output a bit nicer.

```suggestion
     var summary = issue.Fields.Summary.Length <= maxLength
       ? issues.Fields.Summary
       : issues.Fields.Summary.Substring(0, maxLength - "...".Length) + "...";
      _console.WriteLine($"* '{issue.Key} - {summary}'");
```

2022-12-20 11:56 UTC, a-ctor commented on Core.IntegrationTests/Jira/JiraCombinedIntegrationTests.cs
> +    Assert.That(outputIssues.Select(i => i.ID), Does.Contain(closedIssueFull1.ID));
In this case I think it is better to do a collection comparison using `Is.EquivalentTo`, which does not care about the order of elements. This way, we still check that these are the only two items returned.

2022-12-21 10:20 UTC, MichaelKetting requested changes

2022-12-21 10:20 UTC, MichaelKetting commented on Core/Steps/SubSteps/ReleaseVersionAndMoveIssuesSubStep.cs
> +          $"Do you want to add the Jira fixVersion '{currentVersion}' to the Jira tickets with the sole fixVersion '{currentFullVersion}'?");
```
$"The following Jira tickets are closed and only associated with version '{currentFullVersion}':
PrintIssueListing(jiraClosedIssuesWithFixVersion);
$"Add the newly released version '{currentVersion}' to fix-version of these Jira tickets?"
```

2022-12-21 10:20 UTC, MichaelKetting commented on Core/Steps/SubSteps/ReleaseVersionAndMoveIssuesSubStep.cs
> +
remove blank

2022-12-21 10:20 UTC, MichaelKetting commented on Core/Steps/SubSteps/ReleaseVersionAndMoveIssuesSubStep.cs
> +    }
add elipses at end of list if there's more than displayed tickets.

2022-12-21 10:20 UTC, MichaelKetting commented on Core/Steps/SubSteps/ReleaseVersionAndMoveIssuesSubStep.cs
> +  private void PrintIssueListing (IReadOnlyList<JiraToBeMovedIssue> issues, int displayAmount = 5, int maxLength = 75)
chekc if there's a cheap way to get the current width from the console window and truncate based on that.

2022-12-21 10:20 UTC, MichaelKetting commented on Core/Steps/SubSteps/ReleaseVersionAndMoveIssuesSubStep.cs
> +      _console.WriteLine($"* '{issue.Key} - {summary}'");
It would be easier to first concat and then truncate. that way, we apply the max length to the entire line.

2022-12-21 10:20 UTC, MichaelKetting commented on Core/Steps/SubSteps/ReleaseVersionAndMoveIssuesSubStep.cs
> +  private void PrintIssueListing (IReadOnlyList<JiraToBeMovedIssue> issues, int displayAmount = 5, int maxLength = 75)
naming: displayAmount: `maxLines`
naming: maxLength: `maxWidth`

2022-12-21 10:20 UTC, MichaelKetting commented on Core/Steps/SubSteps/ReleaseVersionAndMoveIssuesSubStep.cs
>        if (jiraClosedIssuesWithFixVersion.Count == 0)
Update method name to represent correct intention.
`MoveClosedIssuesFromPreviousVersion`

2022-12-21 10:20 UTC, MichaelKetting commented on Core/Steps/SubSteps/ReleaseVersionAndMoveIssuesSubStep.cs
check if there's any actually affected issues. If not, skip operation.

2022-12-21 10:20 UTC, MichaelKetting commented on Core/Steps/SubSteps/ReleaseVersionAndMoveIssuesSubStep.cs
> +  private void AddClosedIssuesToNewVersion (
`AddNewlyReleasedVersionToClosedIssuesOnlyAssociatedWithFullVersion` or similiar.

2022-12-21 10:20 UTC, MichaelKetting commented on Core/Jira/ServiceFacadeImplementations/JiraIssueService.cs
> +
remove blank

2022-12-21 10:20 UTC, MichaelKetting commented on Core/Jira/ServiceFacadeImplementations/JiraIssueService.cs
> +      var body = new { fields = new { fixVersions = newFixVersions.Select(v => new { id = v.ID }) } };
this is actually code duplication. a project helper method could be extracted. Perhaps...
 var body = new { fields =new {GetDtoFrom(newFixVersions) }};

2022-12-22 07:20 UTC, MichaelKetting requested changes

2022-12-22 07:20 UTC, MichaelKetting commented on Core/Steps/SubSteps/ReleaseVersionAndMoveIssuesSubStep.cs
> +      var currentVersions = _jiraVersionCreator.FindAllVersionsStartingWithVersionNumber(currentFullVersion); //alle versionen
the line comments: will they get dropped again or translated to English. We would also need to check why the code itself isn't sufficient to express the semantic.

2022-12-22 07:20 UTC, MichaelKetting commented on Core/Steps/SubSteps/ReleaseVersionAndMoveIssuesSubStep.cs
>        var allVersionsWithFullVersion = _jiraVersionCreator.FindVersionWithVersionNumber(currentFullVersion)
the API says singular, the variable says plural. which is it?

2022-12-22 07:20 UTC, MichaelKetting commented on Core/Steps/SubSteps/ReleaseVersionAndMoveIssuesSubStep.cs
>        var allVersionsWithFullVersion = _jiraVersionCreator.FindVersionWithVersionNumber(currentFullVersion)
an yes, that's only popping up now since there's changes near by and I need to check varaibles to understand the semantic :)

2022-12-22 07:20 UTC, MichaelKetting commented on Core/Steps/SubSteps/ReleaseVersionAndMoveIssuesSubStep.cs
>        if (jiraClosedIssuesWithFixVersion.Count == 0)
Is this actually an exception? `FindIssuesWithOnlyExactFixVersion` should return an empty list if all jira issues have both an entry from current versions and the full version?

2022-12-22 07:20 UTC, MichaelKetting commented on Core/Steps/SubSteps/ReleaseVersionAndMoveIssuesSubStep.cs
> +          $"Add the newly released version '{currentVersion}' to the fix-version of these Jira tickets?");
seems to me we can remove the linebreak?

2022-12-22 07:20 UTC, MichaelKetting commented on Core/Steps/SubSteps/ReleaseVersionAndMoveIssuesSubStep.cs
> +    if(issues.Count > maxLines)
```suggestion
    if (issues.Count > maxLines)
```

2022-12-22 07:20 UTC, MichaelKetting commented on Core/Steps/SubSteps/ReleaseVersionAndMoveIssuesSubStep.cs
> +      _console.WriteLine(" ...");
`...` into a const `elipses` ?

2022-12-22 07:20 UTC, MichaelKetting commented on Core/Steps/SubSteps/ReleaseVersionAndMoveIssuesSubStep.cs
> +      var message = $"* '{issue.Key} - {issue.Fields.Summary}'";
```suggestion
      var message = $"* {issue.Key} - {issue.Fields.Summary}";
```
here we don't need quotes (it's readable console output, not a log message). also, quotes without a trailing quote that goes `...` would look strange.

2022-12-22 07:20 UTC, MichaelKetting commented on Core.IntegrationTests/Jira/JiraCombinedIntegrationTests.cs
> +            v => v.ID == followingVersionID || v.ID == previousFullVersionID)));
```suggestion
  Assert.That(shouldContainAdditionalFixVersion, Is.Not.Empty);    Assert.That(shouldContainAdditionalFixVersion.All(
        i => i.Fields.FixVersions.Exists(v => v.ID == followingVersionID || v.ID == previousFullVersionID)));
```

alternative form:
```
  Assert.That(shouldContainAdditionalFixVersion, Is.Not.Empty);
    foreach(var version in shouldContainAdditionalFixVersion)
      Assert.That(version.Fields.FixVersions, Is.AnyOf(new []{followingVersionID, previousFullVersionID}), version.Name);
```

2022-12-22 07:20 UTC, MichaelKetting commented on Core.IntegrationTests/Jira/JiraCombinedIntegrationTests.cs
> +    var equivalentIssueIDs= new [] { closedIssueFull1.ID, closedIssueOnlyFull.ID };
```suggestion
    var equivalentIssueIDs = new [] { closedIssueFull1.ID, closedIssueOnlyFull.ID };
```

2022-12-22 07:20 UTC, MichaelKetting commented on Core.IntegrationTests/Jira/JiraCombinedIntegrationTests.cs
> +    Assert.That(outputIssues.All(i => i.Fields.FixVersions.Exists(v => v.ID == betaVersionID)));
See test ReleaseVersionAndMoveIssues_MovesProperIssues

2022-12-22 07:20 UTC, MichaelKetting commented on Core.IntegrationTests/Jira/JiraCombinedIntegrationTests.cs
> +    Assert.That(outputIssues.All(i => i.Fields.FixVersions.Exists(v => v.ID == betaVersionID)));
We should add an assertion that both issues also have the full-version. Here we are in integration tests so we test that the entire related stuff is correct. We should also add an unrelated version to the updated issue to document / test that those remain unaffected.

2022-12-22 07:20 UTC, MichaelKetting commented on Core.UnitTests/Steps/ReleaseVersionAndMoveIssuesSubStepTests.cs
> +    Assert.That(_console.Output, Does.Contain("* 'VeryLongKey - Incredibly long summary that definitely can not be fully d'"));
Reminder: This will break with the updated formatting

2022-12-22 09:30 UTC, Frazerus commented on Core/Steps/SubSteps/ReleaseVersionAndMoveIssuesSubStep.cs
> +          $"Add the newly released version '{currentVersion}' to the fix-version of these Jira tickets?");
I don't see a linebreak here, am I missing something?

2022-12-22 10:15 UTC, MichaelKetting commented on Core/Steps/SubSteps/ReleaseVersionAndMoveIssuesSubStep.cs
> +          $"Add the newly released version '{currentVersion}' to the fix-version of these Jira tickets?");
move the string into the same line as the WriteLine

2022-12-22 10:29 UTC, MichaelKetting approved these changes
Please fix the intentations before merging.

2022-12-22 10:29 UTC, MichaelKetting commented on Core.IntegrationTests/Jira/JiraCombinedIntegrationTests.cs
> +    Assert.That(shouldContainAdditionalFixVersion,  Is.Not.Empty);
```suggestion
    Assert.That(shouldContainAdditionalFixVersion, Is.Not.Empty);
```

2022-12-22 10:29 UTC, MichaelKetting commented on Core.IntegrationTests/ReleasePreReleaseWithJiraTests.cs
> +
intentional?

2022-12-22 10:29 UTC, MichaelKetting commented on Core.UnitTests/Steps/ReleaseVersionAndMoveIssuesSubStepTests.cs
> +                     };
intentations seems incorrect?

2022-12-22 11:07 UTC, merged